packages:
  - apps/**
  - packages/**

catalog:
   '@biomejs/biome': 2.3.11
   '@textlint-ja/textlint-rule-preset-ai-writing': 1.6.1
   'lefthook': 2.0.15
   'npkill': 0.12.2
   'textlint': 15.5.0
   'textlint-rule-preset-ja-technical-writing': 12.0.2
   'turbo': 2.7.4

catalogMode: strict

nodeLinker: 'hoisted'

hoistWorkspacePackages: false

sharedWorkspaceLockfile: false

minimumReleaseAge: 4320
