packages:
  - apps/**
  - packages/**

catalog:
  '@biomejs/biome': 2.3.11
  '@textlint-ja/textlint-rule-preset-ai-writing': 1.6.1
  '@testing-library/jest-dom': ^6.6.3
  '@testing-library/react': ^16.3.1
  '@types/chrome': ^0.0.254
  '@types/node': ^25.0.7
  '@types/react': ^18.3.27
  '@types/react-dom': ^18.3.7
  '@vitejs/plugin-react': ^5.1.2
  lefthook: 2.0.15
  npkill: 0.12.2
  react: ^18.3.1
  react-dom: ^18.3.1
  textlint: 15.5.0
  textlint-rule-preset-ja-technical-writing: 12.0.2
  turbo: 2.7.4
  typescript: ^5.9.3
  ultracite: ^7.0.11
  vite: ^7.3.1
  vitest: ^4.0.17
  jsdom: ^26.0.0

catalogMode: strict

hoistWorkspacePackages: false

minimumReleaseAge: 4320

nodeLinker: hoisted

sharedWorkspaceLockfile: false
