packages:
  - apps/**
  - packages/**

catalog:
  '@0no-co/graphqlsp': ^1.15.2
  '@apollo/client': ^4.1.1
  '@apollo/server': ^5.2.0
  '@as-integrations/express5': ^1.1.2
  '@biomejs/biome': 2.4.4
  '@clerk/backend': ^2.30.0
  '@clerk/chrome-extension': ^2.9.0
  '@clerk/clerk-react': ^5.60.0
  '@cloudflare/workers-types': ^4.20251011.0
  '@getcronit/pylon': ^2.9.5
  '@getcronit/pylon-dev': ^1.0.5
  '@gql.tada/cli-utils': ^1.7.2
  '@graphql-codegen/cli': ^6.1.1
  '@graphql-codegen/client-preset': ^5.2.2
  '@graphql-codegen/introspection': ^5.0.0
  '@graphql-eslint/eslint-plugin': ^4.4.0
  '@graphql-typed-document-node/core': ^3.2.0
  '@hookform/resolvers': ^5.1.0
  '@libsql/client': ^0.17.0
  '@paralleldrive/cuid2': ^3.3.0
  '@playwright/test': ^1.57.0
  '@storybook/addon-links': 10.2.8
  '@storybook/addon-themes': ^10.1.11
  '@storybook/react': 10.2.8
  '@storybook/react-vite': 10.2.8
  '@tailwindcss/typography': 0.5.19
  '@tailwindcss/vite': ^4.1.18
  '@testing-library/jest-dom': ^6.9.1
  '@testing-library/react': ^16.3.2
  '@testing-library/user-event': ^14.6.1
  '@textlint-ja/textlint-rule-preset-ai-writing': 1.6.1
  '@types/chrome': ^0.1.35
  '@types/cors': ^2.8.19
  '@types/express': ^5.0.6
  '@types/node': 25.2.0
  '@types/react': ^19.2.8
  '@types/react-dom': ^19.2.3
  '@vitejs/plugin-react': ^5.1.2
  '@vitest/ui': ^4.0.17
  cors: ^2.8.5
  daisyui: ^5.5.14
  drizzle-kit: ^0.31.5
  drizzle-orm: ^0.45.1
  eslint: ^9.28.0
  eslint-plugin-prefer-arrow-functions: ^3.9.1
  eslint-plugin-react-hooks: ^7.0.1
  eslint-plugin-testing-library: ^7.15.4
  expo: ^55.0.3
  expo-constants: ^55.0.7
  expo-doctor: ^1.18.9
  expo-linking: ^55.0.7
  expo-router: ^55.0.3
  expo-status-bar: ^55.0.4
  express: ^5.2.1
  gql.tada: ^1.9.0
  graphql: ^16.12.0
  jsdom: ^28.0.0
  lefthook: 2.0.15
  msw: ^2.12.7
  msw-storybook-addon: ^2.0.6
  npkill: 0.12.2
  openapi-fetch: ^0.14.0
  openapi-msw: ^2.0.0
  openapi-typescript: ^7.9.1
  react: 19.2.0
  react-dom: 19.2.0
  react-error-boundary: ^6.1.0
  react-hook-form: ^7.58.1
  react-markdown: ^10.1.0
  react-native: ^0.83.2
  react-native-safe-area-context: ~5.6.2
  react-native-screens: ~4.23.0
  react-native-web: ^0.21.2
  remark-gfm: ^4.0.1
  scaffdog: ^4.1.0
  storybook: 10.2.8
  swr: ^2.3.4
  tailwindcss: ^4.1.18
  textlint: 15.5.1
  textlint-rule-preset-ja-technical-writing: 12.0.2
  tsx: ^4.21.0
  turbo: 2.8.9
  typescript: ^5.9.3
  typescript-eslint: ^8.33.0
  ultracite: ^7.0.12
  vite: ^7.3.1
  vite-plugin-dts: ^4.5.0
  vitest: ^4.0.17
  wrangler: ^4.43.0
  zod: ^3.25.51

catalogMode: strict

hoistWorkspacePackages: false

minimumReleaseAge: 4320

minimumReleaseAgeExclude:
  - '@expo/*'
  - babel-preset-expo
  - expo
  - expo-*
  - react-native*

nodeLinker: hoisted

sharedWorkspaceLockfile: false
