packages:
  - apps/**
  - packages/**

catalog:
  '@eslint/js': ^9.28.0
  '@0no-co/graphqlsp': ^1.15.2
  '@apollo/client': ^4.1.1
  '@apollo/server': ^5.2.0
  '@as-integrations/express5': ^1.1.2
  '@biomejs/biome': 2.3.11
  '@cloudflare/workers-types': ^4.20251011.0
  '@getcronit/pylon': ^2.9.5
  '@getcronit/pylon-dev': ^1.0.5
  '@gql.tada/cli-utils': ^1.7.2
  '@graphql-codegen/cli': ^6.1.1
  '@graphql-codegen/client-preset': ^5.2.2
  '@graphql-codegen/introspection': ^5.0.0
  '@graphql-typed-document-node/core': ^3.2.0
  '@libsql/client': ^0.15.15
  '@paralleldrive/cuid2': ^2.2.2
  '@playwright/test': ^1.57.0
  '@storybook/addon-links': 10.1.11
  '@storybook/addon-themes': ^10.1.11
  '@storybook/react': 10.1.11
  '@storybook/react-vite': 10.1.11
  '@tailwindcss/typography': 0.5.19
  '@tailwindcss/vite': ^4.1.18
  '@testing-library/jest-dom': ^6.9.1
  '@testing-library/react': ^16.3.2
  '@textlint-ja/textlint-rule-preset-ai-writing': 1.6.1
  '@types/chrome': ^0.1.35
  '@types/cors': ^2.8.19
  '@types/express': ^5.0.6
  '@types/node': 25.0.9
  '@types/react': ^19.2.8
  '@types/react-dom': ^19.2.3
  '@vitejs/plugin-react': ^5.1.2
  '@vitest/ui': ^4.0.17
  cors: ^2.8.5
  daisyui: ^5.5.14
  drizzle-kit: ^0.31.5
  drizzle-orm: ^0.44.6
  eslint: ^9.28.0
  express: ^5.2.1
  gql.tada: ^1.9.0
  graphql: ^16.12.0
  jsdom: ^27.4.0
  lefthook: 2.0.15
  msw: ^2.12.7
  npkill: 0.12.2
  openapi-fetch: ^0.14.0
  openapi-msw: ^1.3.0
  openapi-typescript: ^7.9.1
  react: ^19.2.3
  react-dom: ^19.2.3
  scaffdog: ^4.1.0
  storybook: 10.1.11
  tailwindcss: ^4.1.18
  textlint: 15.5.1
  textlint-rule-preset-ja-technical-writing: 12.0.2
  tsx: ^4.21.0
  turbo: 2.7.5
  typescript: ^5.9.3
  typescript-eslint: ^8.34.0
  ultracite: ^7.0.12
  vite: ^7.3.1
  vite-plugin-dts: ^4.5.0
  vitest: ^4.0.17
  wrangler: ^4.43.0

catalogMode: strict

hoistWorkspacePackages: false

minimumReleaseAge: 4320

nodeLinker: hoisted

sharedWorkspaceLockfile: false
