packages:
  - apps/**
  - packages/**

catalog:
  '@apollo/server': ^5.2.0
  '@as-integrations/express5': ^1.1.2
  '@biomejs/biome': 2.3.11
  '@playwright/test': ^1.57.0
  '@storybook/addon-links': 10.1.11
  '@storybook/addon-themes': ^10.1.11
  '@storybook/react': 10.1.11
  '@storybook/react-vite': 10.1.11
  '@tailwindcss/typography': 0.5.19
  '@tailwindcss/vite': ^4.1.18
  '@testing-library/jest-dom': ^6.9.1
  '@testing-library/react': ^16.3.2
  '@textlint-ja/textlint-rule-preset-ai-writing': 1.6.1
  '@types/chrome': ^0.1.35
  '@types/cors': ^2.8.19
  '@types/express': ^5.0.6
  '@types/node': 25.0.9
  '@types/react': ^19.2.8
  '@types/react-dom': ^19.2.3
  '@vitejs/plugin-react': ^5.1.2
  cors: ^2.8.5
  daisyui: ^5.5.14
  express: ^5.2.1
  graphql: ^16.12.0
  jsdom: ^27.4.0
  lefthook: 2.0.15
  npkill: 0.12.2
  react: ^19.2.3
  react-dom: ^19.2.3
  storybook: 10.1.11
  tailwindcss: ^4.1.18
  textlint: 15.5.1
  textlint-rule-preset-ja-technical-writing: 12.0.2
  tsx: ^4.21.0
  turbo: 2.7.5
  typescript: ^5.9.3
  ultracite: ^7.0.11
  vite: ^7.3.1
  vite-plugin-dts: ^4.5.0
  vitest: ^4.0.17

catalogMode: strict

hoistWorkspacePackages: false

minimumReleaseAge: 4320

nodeLinker: hoisted

sharedWorkspaceLockfile: false
