/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        // gluestack-ui v3 semantic color tokens mapped to CSS custom properties
        primary: {
          0: "rgb(var(--color-primary-0) / <alpha-value>)",
          50: "rgb(var(--color-primary-50) / <alpha-value>)",
          100: "rgb(var(--color-primary-100) / <alpha-value>)",
          200: "rgb(var(--color-primary-200) / <alpha-value>)",
          300: "rgb(var(--color-primary-300) / <alpha-value>)",
          400: "rgb(var(--color-primary-400) / <alpha-value>)",
          500: "rgb(var(--color-primary-500) / <alpha-value>)",
          600: "rgb(var(--color-primary-600) / <alpha-value>)",
          700: "rgb(var(--color-primary-700) / <alpha-value>)",
          800: "rgb(var(--color-primary-800) / <alpha-value>)",
          900: "rgb(var(--color-primary-900) / <alpha-value>)",
          950: "rgb(var(--color-primary-950) / <alpha-value>)",
        },
        background: {
          0: "rgb(var(--color-background-0) / <alpha-value>)",
          50: "rgb(var(--color-background-50) / <alpha-value>)",
          100: "rgb(var(--color-background-100) / <alpha-value>)",
          200: "rgb(var(--color-background-200) / <alpha-value>)",
          300: "rgb(var(--color-background-300) / <alpha-value>)",
          400: "rgb(var(--color-background-400) / <alpha-value>)",
          500: "rgb(var(--color-background-500) / <alpha-value>)",
          600: "rgb(var(--color-background-600) / <alpha-value>)",
          700: "rgb(var(--color-background-700) / <alpha-value>)",
          800: "rgb(var(--color-background-800) / <alpha-value>)",
          900: "rgb(var(--color-background-900) / <alpha-value>)",
          950: "rgb(var(--color-background-950) / <alpha-value>)",
        },
        typography: {
          0: "rgb(var(--color-typography-0) / <alpha-value>)",
          50: "rgb(var(--color-typography-50) / <alpha-value>)",
          100: "rgb(var(--color-typography-100) / <alpha-value>)",
          200: "rgb(var(--color-typography-200) / <alpha-value>)",
          300: "rgb(var(--color-typography-300) / <alpha-value>)",
          400: "rgb(var(--color-typography-400) / <alpha-value>)",
          500: "rgb(var(--color-typography-500) / <alpha-value>)",
          600: "rgb(var(--color-typography-600) / <alpha-value>)",
          700: "rgb(var(--color-typography-700) / <alpha-value>)",
          800: "rgb(var(--color-typography-800) / <alpha-value>)",
          900: "rgb(var(--color-typography-900) / <alpha-value>)",
          950: "rgb(var(--color-typography-950) / <alpha-value>)",
        },
        error: {
          0: "rgb(var(--color-error-0) / <alpha-value>)",
          50: "rgb(var(--color-error-50) / <alpha-value>)",
          100: "rgb(var(--color-error-100) / <alpha-value>)",
          200: "rgb(var(--color-error-200) / <alpha-value>)",
          300: "rgb(var(--color-error-300) / <alpha-value>)",
          400: "rgb(var(--color-error-400) / <alpha-value>)",
          500: "rgb(var(--color-error-500) / <alpha-value>)",
          600: "rgb(var(--color-error-600) / <alpha-value>)",
          700: "rgb(var(--color-error-700) / <alpha-value>)",
          800: "rgb(var(--color-error-800) / <alpha-value>)",
          900: "rgb(var(--color-error-900) / <alpha-value>)",
          950: "rgb(var(--color-error-950) / <alpha-value>)",
        },
        success: {
          0: "rgb(var(--color-success-0) / <alpha-value>)",
          50: "rgb(var(--color-success-50) / <alpha-value>)",
          100: "rgb(var(--color-success-100) / <alpha-value>)",
          200: "rgb(var(--color-success-200) / <alpha-value>)",
          300: "rgb(var(--color-success-300) / <alpha-value>)",
          400: "rgb(var(--color-success-400) / <alpha-value>)",
          500: "rgb(var(--color-success-500) / <alpha-value>)",
          600: "rgb(var(--color-success-600) / <alpha-value>)",
          700: "rgb(var(--color-success-700) / <alpha-value>)",
          800: "rgb(var(--color-success-800) / <alpha-value>)",
          900: "rgb(var(--color-success-900) / <alpha-value>)",
          950: "rgb(var(--color-success-950) / <alpha-value>)",
        },
      },
    },
  },
  plugins: [],
};
